server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
spring:
  application:
    name: student-client
  boot:
    admin:
      username: admin
      password: admin
      url: http://localhost:9889